const nav_And_Form = "<mat-sidenav-container class=\"sidenav-container\">\n"
    		+ "    <!-- Side Navigation -->\n"
    		+ "    <mat-sidenav #sidenav [(opened)]=\"opened\" mode=\"side\" class=\"sidenav\" [style.width.px]=\"opened ? 180 : 64\">\n"
    		+ "      <mat-nav-list>\n"
    		+ "        <a mat-list-item href=\"#\">\n"
    		+ "          <mat-icon>home</mat-icon>\n"
    		+ "         @if(opened) { <span>Home</span>   }\n"
    		+ "        </a>\n"
    		+ "        <a mat-list-item href=\"#\">\n"
    		+ "          <mat-icon>info</mat-icon>\n"
    		+ "         @if(opened) { <span>About</span>  }\n"
    		+ "        </a>\n"
    		+ "        <a mat-list-item href=\"#\">\n"
    		+ "          <mat-icon>build</mat-icon>\n"
    		+ "         @if(opened) { <span>Services</span> }\n"
    		+ "        </a>\n"
    		+ "        <a mat-list-item href=\"#\">\n"
    		+ "          <mat-icon>contact_mail</mat-icon>\n"
    		+ "         @if(opened) { <span>Contact</span>}\n"
    		+ "        </a>\n"
    		+ "      </mat-nav-list>\n"
    		+ "    </mat-sidenav>\n"
    		+ "  \n"
    		+ "    <!-- Main Content -->\n"
    		+ "    <mat-sidenav-content class=\"main-content\">\n"
    		+ "      <mat-toolbar color=\"primary\">\n"
    		+ "        <button mat-icon-button (click)=\"opened = !opened\">\n"
    		+ "          <mat-icon>{{ opened ? 'close' : 'menu' }}</mat-icon>\n"
    		+ "        </button>\n"
    		+ "        <span class=\"text-warning\">Caculated Bliss</span>\n"
    		+ "      </mat-toolbar>\n"
    		+ "      <div class=\"content\">\n"
    		+ "        <div class=\"container\">\n"
    		+ "          <div class=\"container mt-5\" style=\"background-color: purple;\">\n"
    		+ "            <div class=\"row justify-content-center\">\n"
    		+ "              <div class=\"col-md-6\">\n"
    		+ "                <div class=\"card\">\n"
    		+ "                  <div class=\"card-header bg-warning text-white text-center\">\n"
    		+ "                    <h3 style=\"color: rgba(80, 76, 76, 0.688);\">Artist Submission</h3>\n"
    		+ "                    <h5 style=\"color: rgba(84, 56, 41, 0.468);\">Please click the submit button only <span style=\"color: rgba(170, 78, 78, 0.411);\">once</span>.</h5>\n"
    		+ "                  </div>\n"
    		+ "                  <div class=\"card-body\">\n"
    		+ "                    \n"
    		+ "                    \n"
    		+ "                    <form (ngSubmit)=\"onSubmitArtist()\" #artistForm=\"ngForm\">\n"
    		+ "                      \n"
    		+ "                      <div class=\"form-group mb-3\">\n"
    		+ "                        <label for=\"email\" class=\"form-label\">Email</label>\n"
    		+ "                        <input\n"
    		+ "                          type=\"email\"\n"
    		+ "                          id=\"email\"\n"
    		+ "                          class=\"form-control\"\n"
    		+ "                          [(ngModel)]=\"artist.email\"\n"
    		+ "                          name=\"email\"\n"
    		+ "                          required\n"
    		+ "                        />\n"
    		+ "                      </div>\n"
    		+ "                      <div class=\"form-group mb-3\">\n"
    		+ "                        <label for=\"email\" class=\"form-label\">Bio</label>\n"
    		+ "                        <input\n"
    		+ "                          type=\"bio\"\n"
    		+ "                          id=\"bio\"\n"
    		+ "                          class=\"form-control\"\n"
    		+ "                          [(ngModel)]=\"artist.bio\"\n"
    		+ "                          name=\"email\"\n"
    		+ "                          required\n"
    		+ "                        />\n"
    		+ "                      </div>\n"
    		+ "                      \n"
    		+ "                      <div class=\"form-group mb-3\">\n"
    		+ "                        <label for=\"name\" class=\"form-label\">Name</label>\n"
    		+ "                        <input\n"
    		+ "                          type=\"text\"\n"
    		+ "                          id=\"name\"\n"
    		+ "                          class=\"form-control\"\n"
    		+ "                          [(ngModel)]=\"artist.name\"\n"
    		+ "                          name=\"name\"\n"
    		+ "                          required\n"
    		+ "                        />\n"
    		+ "                      </div>\n"
    		+ "                      \n"
    		+ "                      <button type=\"submit\" class=\"btn custom-purple w-100\" [disabled]=\"!artistForm.form.valid\">\n"
    		+ "                        Submit\n"
    		+ "                      </button>\n"
    		+ "                      <a href=\"http://click.linksynergy.com/fs-bin/click?id=tAaIuszgIHY&offerid=311675&type=3&subid=0&LSNSUBSITE=LSNSUBSITE\" class=\"text-warning\">Rakuten Advertising Welcome Program</a>\n"
    		+ "                    </form>\n"
    		+ "                  </div>\n"
    		+ "                </div>\n"
    		+ "              </div>\n"
    		+ "            </div>\n"
    		+ "          </div>\n"
    		+ "          \n"
    		+ "          </div>\n"
    		+ "      </div>\n"
    		+ "    </mat-sidenav-content>\n"
    		+ "  </mat-sidenav-container>\n"
    		+ "  \n"
    		+ "  \n"
    		+ "  \n"
    		+ "  ";

			// Push the content to the HTML page by inserting it into a specific element
document.addEventListener('DOMContentLoaded', () => {
    // Find the element in which you want to insert the content
    const container = document.getElementById('nav-and-form-content');
    
    // Insert the content inside the element
    if (container) {
        container.innerHTML = nav_And_Form;
    }
});